# The port where the server will listen for browser connections.
# Default: 8501
# port = 8501

# The base path for the URL where Streamlit should be served from.
# Default: ""
# baseUrlPath = ""

[browser]

# Whether to send usage statistics to Streamlit.
# Default: true
gatherUsageStats = false

# Port where users should point their browsers in order to connect to the app.
# This is used to: - Set the correct URL for CORS and XSRF protection purposes. - Show the URL on the terminal - Open the browser
# Default: whatever value is set in server.port.
# serverPort = 8501

[theme]

# The preset Streamlit theme that your custom theme inherits from. One of "light" or "dark".
base = "light"

